- EGI.md
Updates EGI steps and fixes https://github.com/pangeo-data/pangeo-eosc/issues/7
> Update EGI steps

- EGI.md
Fixes https://github.com/pangeo-data/pangeo-eosc/issues/8
> Add dask cluster timeout

- EGI.md
Related to comments made in #22.
cc @sebastian-luna-valero.
> Update EGI Pangeo deployement doc for Elastic and Helm

- WEB-Object_storage-Creation.md
Fixes https://github.com/pangeo-data/pangeo-eosc/issues/35
> Add table with permissions to access object storage

- EGI.md
With Elastic Kubernetes last information.
With Worker memory limitations discussion.
> Update platform installation documentation

- EGI.md
Thanks to @micafer debugging, some tips exchanged by email.
> Adding troubleshooting documentatio for K8S Elastic scaling

- providers/kubernetes/README.md
- providers/kubernetes/daskhub-secrets.yaml
- providers/kubernetes/daskhub.yaml
This should help managing the deployment more securely.
> Separate config and secrets in values.yaml for DaskHub

- providers/kubernetes/README.md
- providers/kubernetes/binderhub/binderhub-secrets.yaml
- providers/kubernetes/binderhub/binderhub.yaml
- providers/kubernetes/binderhub/dask-gateway-secrets.yaml
- providers/kubernetes/binderhub/dask-gateway.yaml
- users/users-getting-started.md
Merging this instead of: https://github.com/pangeo-data/pangeo-eosc/pull/46
> Add Binder

- providers/kubernetes/daskhub.yaml
Update dask cluster resource limits:
https://gateway.dask.org/resource-limits.html
> Dask limits

- providers/kubernetes/daskhub.yaml
Fixes https://github.com/pangeo-data/pangeo-eosc/issues/61
> Update pangeo-notebook image

- users/users-getting-started.md
Reverts pangeo-data/pangeo-eosc#60
> Revert "Update users-getting-started.md"

- providers/kubernetes/daskhub.yaml
Fixes https://github.com/pangeo-data/pangeo-eosc/issues/63
xref: https://github.com/pangeo-data/pangeo-docker-images/blob/2023.12.17/pangeo-notebook/conda-linux-64.lock#L643
> Update container images

- providers/kubernetes/daskhub.yaml
As agreed in https://github.com/pangeo-data/pangeo-eosc/pull/68
> Deploy custom DaskHub homepage

- README.md
> add bids paper

- README.md
- policies/privacy-policy.html
- providers/kubernetes/README.md
- providers/kubernetes/daskhub-secrets.yaml
- providers/kubernetes/daskhub.yaml
- providers/providers-getting-started.md
- templates/login.html
- users/users-getting-started.md
Update docs and add warning message at login page.
> Pangeo@EOSC: scheduled maintenance window on 7th May, 2.30pm - 3.30pm CEST

- providers/kubernetes/README.md
- providers/kubernetes/binderhub/binderhub.yaml
- providers/kubernetes/binderhub/dask-gateway.yaml
- providers/kubernetes/daskhub.yaml
in preparation of the upcoming courses Geo-open-hack and IGARSS 2024
> update docker images

- README.md
The PR adds the paper "Improving the reproducibility in geoscientific papers: lessons learned from a Hackathon in climate science" related to the 2023 Climate Informatics Reproducibility Challenge.
> Add position paper of the CICR23

- providers/kubernetes/daskhub.yaml
Based on the discussion in https://github.com/pangeo-data/pangeo-eosc/issues/96#issuecomment-2776191842
I searched in https://github.com/search?q=repo%3A2i2c-org%2Finfrastructure%20unlisted_choice&type=code
and came up with these changes to enable the bring your own image option.
> Bring your own image

- providers/kubernetes/minio/minio.yaml
xref: https://github.com/minio/minio/issues/20146
> Increase MINIO_STS_DURATION

- README.md
xref: https://github.com/digital-earths-global-hackathon/hk25-teams/pull/34
> WCRP Global KM scale hackathon

- providers/kubernetes/daskhub.yaml
adding a fixed image and also latest for openscapes
> Update daskhub.yaml openscapes images

- users/users-getting-started.md
This is now asked after the migration to the new EGI Check-in system.
> Specify group role to enrol

- users/how-to/object-storage-openstack-cli.md
- users/how-to/object-storage-openstack-horizon.md
Fixes https://github.com/pangeo-data/pangeo-eosc/issues/111
> Update CESNET config after migration to new site

- providers/kubernetes/daskhub.yaml
Instead of "latest" we are now using "main" and "develop" as tags
> Update daskhub.yaml with main and develop protocoast images
